Sending call request - completed
Koci0/Nokia-PK-2021 pull request #22
Opened 2021-05-15 14:22 UTC by jakjare

2021-05-15 20:05 UTC, Koci0 approved these changes
Nice job, we just need to remember to handle the TODOs before the demo.

2021-05-17 09:13 UTC, KazdMomi approved these changes

2021-05-17 09:39 UTC, ParleJe requested changes

2021-05-17 09:39 UTC, ParleJe commented on UE/Application/Ports/UserPort.cpp
> +}
```suggestion
}

```

2021-05-17 10:04 UTC, ParleJe approved these changes

2021-05-17 10:05 UTC, merged